# General server config
server:
  #  path: /
  #  proxy: true
  host: "0.0.0.0"
  port: 8080

# Local paths to modules and config
modules:
  plugins:
    provider:
      type: folder
      path: /data/pylon/plugins
  #
  requirements:
    mode: relaxed
    provider:
      type: folder
      path: /data/pylon/requirements
  #
  config:
    provider:
      type: folder
      path: /data/pylon/configs
  #
  preload:
    market:
      provider:
        type: git
        delete_git_dir: false
        depth: null
      source: https://github.com/carrier-io/market.git

configs:
  market:
    preordered_plugins:
      - auth
      - theme
      - shared
      - design-system
    plugin_repo:
      - type: config
        data:
          theme:
            source:
              type: git
              source: "https://github.com/carrier-io/theme.git"
              branch: next
            objects:
              metadata: "https://raw.githubusercontent.com/carrier-io/theme/next/metadata.json"
          shared:
            source:
              type: git
              source: "https://github.com/carrier-io/shared.git"
              branch: next
            objects:
              metadata: "https://raw.githubusercontent.com/carrier-io/shared/next/metadata.json"
          design-system:
            source:
              type: git
              source: "https://github.com/carrier-io/design-system.git"
              branch: next
            objects:
              metadata: "https://raw.githubusercontent.com/carrier-io/design-system/next/metadata.json"
          auth:
            source:
              type: git
              source: "https://github.com/carrier-io/auth.git"
              branch: dummy
            objects:
              metadata: "https://raw.githubusercontent.com/carrier-io/auth/dummy/metadata.json"
      - type: resource
        name: data/plugins.json

# Settings for Flask application
application:
  # EXPLAIN_TEMPLATE_LOADING: true
  # Sessions
  SECRET_KEY: SecretDevKeyForLocalUseOnlyChangedOnProd
  SESSION_COOKIE_NAME: session_id

# dulwich git manager
git_manager:
  default:
    username:
    password:
    key:
    key_data:
