
# General server config
server:
#  path: /
#  proxy: true
  host: "0.0.0.0"
  port: 8080

# Local paths to modules and config
modules:
  plugins:
    provider: archive
    storage: minio
    container: modules
  requirements:
    provider: plain
    storage: local
    container: reqs
    strict: true
  config:
    provider: plain
    storage: local
    container: cfgs
  preload:
    market:
      source:
        provider: git
        url: https://github.com/carrier-io/market.git
        branch: main
      metadata:
        provider: http
        url: https://raw.githubusercontent.com/carrier-io/market/main/metadata.json

development:
  modules: plugins
  config: config

# Session storage
sessions:
  redis:
    host: {{ IP_HERE }}
    password: password
  prefix: pylon_session_

# Traefik config
traefik:
  redis:
    host: {{ IP_HERE }}
    password: password
  rootkey: traefik
  entrypoint: http
  rule: PathPrefix(`/`)
  node_name: core
  node_hostname: pylon
  # node_url: http://pylon:8080

# Events queue
events:
  rabbitmq:
    host: {{ IP_HERE }}
    port: 5672
    user: user
    password: password
    vhost: carrier
    queue: events
    hmac_key: key
    hmac_digest: sha512

# Module/config storage
storage:
  minio:
    endpoint: {{ IP_HERE }}:9000
    access_key: admin
    secret_key: password
    secure: false
  local:
    path: /tmp/local

# Loki logging settings
loki:
  buffering: true
  buffer_capacity: 20
  include_node_name: true
  include_level_name: true
  include_logger_name: true
  verify: true
  url: {{ IP_HERE }}:3100


# Settings for Flask application
# application:
#   EXPLAIN_TEMPLATE_LOADING: true

# dulwich git manager
git_manager:
  default:
    username:
    password:
    key:
    key_data:
