apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ index .Values "grafana-loki" "fullnameOverride" }}-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - http:
        paths:
          - path: "/loki"
            pathType: Prefix
            backend:
              service:
                name: {{ index .Values "grafana-loki" "fullnameOverride" }}
                port:
                  name: http