apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.keycloak.fullnameOverride }}-ingress
spec:
  rules:
    - http:
        paths:
          - path: "/auth"
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.keycloak.fullnameOverride }}
                port:
                  name: http