apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.services.pylon.name }}-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
