apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.services.pylon.name }}-ingress
  annotations:
#    nginx.ingress.kubernetes.io/auth-url: <auth-url>
    nginx.ingress.kubernetes.io/auth-signin: http://{{ .Values.services.pylon_auth.name }}:{{ .Values.services.pylon_auth.port }}/forward-auth/auth?target=rpc
    nginx.ingress.kubernetes.io/auth-response-headers: X-Auth-Type,X-Auth-ID,X-Auth-Reference
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ .Values.services.pylon.name }}
            port:
              number: {{ .Values.services.pylon.port }}
#    host: {{ .Values.global.app.host }}
